### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by BachiMjavanadze** [AdmiralSnyder/VarCodeLensExtension#1]
stopped working :(
I'm on Windows 10, VisualStudio2022 (v.17.4.3)
The line for CodeLens is selected but nothing is shown:
![image](https://user-images.githubusercontent.com/38082501/208920811-dd41d1b1-8624-48ae-bfef-c6755ed9ce7e.png)

**Comment by BachiMjavanadze** [comment]
two times reinstalled, third time it begin showing codelence but after changing condolence font size to 12 it stopped work (reinstalling doesn't helps):

![image](https://user-images.githubusercontent.com/38082501/208922222-307b5d7a-e43c-45fb-bc72-f82738777ae4.png)

**Comment by AdmiralSnyder** [comment]
hey, can we trace how the "not working" happened? did it work previously? what changed on your side?
also, do you have other extensions installed that might conflict?
can you try opening a second VS and attaching to it to see if there's an exception in my code somewhere (though I should catch them all...)
I'm on discord, regularly (just at work right now and thus sometimes not at my desk...)
looking forward to a reply :-)

**Comment by BachiMjavanadze** [comment]
Yes, I use many extentions but previously it worked for me

**Comment by BachiMjavanadze** [comment]
I think I've found the bug place: extension makes cash and this cash makes problem. after changing font size is stops works as I mentioned above but if you delete `.vs`, `bin` and `obj` folders it begins working again

**Comment by BachiMjavanadze** [comment]
now i think deleting of only `.vs` folder is enough
