### ISSUE TITLE
Open sourcing the project

### ISSUE THREAD

**Issue by kharai-tor** [AdmiralSnyder/VarCodeLensExtension#2]
Any chance you could open source the project? It would be a great learning resource as I'm trying to figure out how to build a CodeLens extension of my own. I haven't been able to find good resources out there that show how a CodeLens extension that displays information based on the C# code can be built. I'm aware of an example in this repo - https://github.com/microsoft/VSSDK-Extensibility-Samples but it's not a sufficient one.

Any help would be much appreciated.

**Comment by kharai-tor** [comment]
Never mind

**Comment by AdmiralSnyder** [comment]
hey, sorry, i got busy with real life this first quarter, so your issue got totally swept under the rug.
so, if you wanna dialog regarding building your own extension, just keep the conversation going :-)

**Comment by kharai-tor** [comment]
It's ok. I found some other examples online and I'll try to take it from there. Still appreciate your response.
